SET search_path TO mineral_water_catalog;

INSERT INTO manufacturer (name, country) VALUES
('BORJOMI GEO', 'GEORGIA'),
('NARZAN AO', 'RUSSIA'),
('ESSENTUKI WATER', 'RUSSIA'),
('DONAT MG', 'SLOVENIA'),
('GEROLSTEINER', 'GERMANY'),
('EVIAN GROUP', 'FRANCE'),
('SAN PELLEGRINO', 'ITALY'),
('ARHYIZ COMPANY', 'RUSSIA'),
('SLAVYANOVSKAYA', 'RUSSIA'),
('SMIRNOVSKAYA', 'RUSSIA'),
('DJERMUK WATER', 'ARMENIA');

INSERT INTO water (water_name, type, manufacturer_id) VALUES
('BORJOMI CLASSIC', 'SULFATE-BICARBONATE', 1),
('NARZAN GENERAL', 'SULFATE-BICARBONATE', 2),
('ESSENTUKI 4', 'CHLORIDE-BICARBONATE', 3),
('ESSENTUKI 17', 'CHLORIDE-BICARBONATE', 3),
('DONAT MG', 'MAGNESIUM', 4),
('GEROLSTEINER NATUR', 'BICARBONATE', 5),
('EVIAN NATURAL', 'BICARBONATE', 6),
('SAN PELLEGRINO', 'SULFATE', 7),
('ARHYIZ PREMIUM', 'BICARBONATE', 8),
('SLAVYANOVSKAYA', 'SULFATE-BICARBONATE', 9),
('SMIRNOVSKAYA', 'SULFATE-BICARBONATE', 10),
('DJERMUK ORIGINAL', 'SULFATE-BICARBONATE', 11);

INSERT INTO indication (indication_name, description) VALUES
('GASTRITIS', 'CHRONIC GASTRITIS WITH NORMAL ACIDITY'),
('PEPTIC ULCER', 'STOMACH AND DUODENUM ULCER'),
('DIABETES', 'DIABETES MELLITUS TYPE 2'),
('OBESITY', 'METABOLIC DISORDERS AND OBESITY'),
('KIDNEY DISEASE', 'KIDNEY STONES AND UROLITHIASIS'),
('LIVER DISEASE', 'LIVER AND BILE DUCT DISEASES'),
('CARDIOVASCULAR', 'CARDIOVASCULAR DISEASES'),
('OSTEOPOROSIS', 'BONE DISEASES AND OSTEOPOROSIS'),
('MAGNESIUM DEFICIENCY', 'MAGNESIUM DEFICIENCY CONDITIONS'),
('RESPIRATORY', 'CHRONIC RESPIRATORY DISEASES'),
('SKIN DISEASES', 'DERMATOLOGICAL CONDITIONS'),
('STRESS', 'NERVOUS SYSTEM DISORDERS');

INSERT INTO water_indication (water_id, indication_id) VALUES
(1, 1),  -- BORJOMI - GASTRITIS
(1, 2),  -- BORJOMI - PEPTIC ULCER
(1, 6),  -- BORJOMI - LIVER DISEASE
(2, 1),  -- NARZAN - GASTRITIS
(2, 7),  -- NARZAN - CARDIOVASCULAR
(3, 1),  -- ESSENTUKI 4 - GASTRITIS
(3, 3),  -- ESSENTUKI 4 - DIABETES
(3, 4),  -- ESSENTUKI 4 - OBESITY
(4, 2),  -- ESSENTUKI 17 - PEPTIC ULCER
(4, 5),  -- ESSENTUKI 17 - KIDNEY DISEASE
(5, 8),  -- DONAT MG - OSTEOPOROSIS
(5, 9),  -- DONAT MG - MAGNESIUM DEFICIENCY
(5, 7),  -- DONAT MG - CARDIOVASCULAR
(6, 8),  -- GEROLSTEINER - OSTEOPOROSIS
(6, 1),  -- GEROLSTEINER - GASTRITIS
(7, 12), -- EVIAN - STRESS
(7, 11), -- EVIAN - SKIN DISEASES
(8, 6),  -- SAN PELLEGRINO - LIVER DISEASE
(8, 4),  -- SAN PELLEGRINO - OBESITY
(9, 1),  -- ARHYIZ - GASTRITIS
(9, 10), -- ARHYIZ - RESPIRATORY
(10, 1), -- SLAVYANOVSKAYA - GASTRITIS
(10, 2), -- SLAVYANOVSKAYA - PEPTIC ULCER
(10, 6), -- SLAVYANOVSKAYA - LIVER DISEASE
(11, 1), -- SMIRNOVSKAYA - GASTRITIS
(11, 12),-- SMIRNOVSKAYA - STRESS
(12, 1), -- DJERMUK - GASTRITIS
(12, 3), -- DJERMUK - DIABETES
(12, 11);-- DJERMUK - SKIN DISEASES
